# Generated by Django 4.1.5 on 2023-01-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='additional_column',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
