# Generated by Django 4.1.5 on 2023-02-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_score_additional_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_multiple',
            field=models.IntegerField(default=0),
        ),
    ]
